llm_providers:
  openai_gpt35:
    provider: "openai"
    model: "gpt-3.5-turbo"
    temperature: 0.7
    max_tokens: 4000
  
  openai_gpt4o_mini:
    provider: "openai"
    model: "gpt-4o-mini"
    temperature: 0.7
    max_tokens: 4000

  anthropic_claude_35:
    provider: "anthropic"
    model: "claude-3-5-sonnet-latest"
    temperature: 0.7
    max_tokens: 4000
    
judge_llm:
  provider: "openai"
  model: "gpt-4o"
  temperature: 0.1
  max_tokens: 4000

apis:
  weather:
    provider: "openweathermap"
    api_key: "${WEATHER_API_KEY}"
  maps:
    provider: "googlemaps"
    api_key: "${MAPS_API_KEY}"
  search:
    provider: "serpapi"
    api_key: "${SERP_API_KEY}"

evaluation:
  output_file: "evaluation_results.json"
  metrics:
    - "accuracy"          # How accurately the agent addresses the user request
    - "relevance"         # How relevant the recommendations are to user preferences
    - "completeness"      # How complete the travel plan is
    - "usefulness"        # How useful the information would be for the traveler
    - "creativity"        # How creative and personalized the suggestions are
  scale_min: 1
  scale_max: 10